import spacy

print(spacy.explain("PROPN"))
print(spacy.explain("NOUN"))
print(spacy.explain("ADJ"))
print(spacy.explain("NNP"))
print(spacy.explain("NN"))
print(spacy.explain("AUX"))
print(spacy.explain("VBZ"))
print(spacy.explain("VERB"))
print(spacy.explain("ADP"))
print(spacy.explain("SYM"))
print(spacy.explain("NUM"))
print(spacy.explain("CD"))
print(spacy.explain("VBG"))
print(spacy.explain("ROOT"))

print(spacy.explain("FAC"))
print(spacy.explain("NORP"))
print(spacy.explain("GPE"))
print(spacy.explain("PRODUCT"))
print(spacy.explain("EVENT"))
print(spacy.explain("PERSON"))
print(spacy.explain("ORG"))
print(spacy.explain("LOC"))
print(spacy.explain("DATE"))
print(spacy.explain("TIME"))
print(spacy.explain("WORK_OF_ART"))
