[project]
enable_telemetry = false
user_env = []
session_timeout = 50000
cache = false

[features]
prompt_playground = true
unsafe_allow_html = false
latex = false

[UI]
name = "Assistant"
show_readme_as_default = true
default_collapse_content = true
default_expand_messages = false
hide_cot = false
custom_css = "http://127.0.0.1:5000/static/style.css"

[meta]
generated_by = "1.0.100"

[features.multi_modal]
enabled = true
accept = [ "*/*",]
max_files = 20
max_size_mb = 500

[features.speech_to_text]
enabled = false

[UI.theme]
layout = "wide"
